### ISSUE TITLE
first paper for MSL and SMAP

### ISSUE THREAD

**Issue by mohayl** [elisejiuqizhang/TS-AD-Datasets#1]
These datasets are first used in this paper:
Detecting Spacecraft Anomalies Using LSTMs and Nonparametric Dynamic Thresholding

**Comment by elisejiuqizhang** [comment]
I was quoting the NASA paper I think? If you'd click into the link you would find their arXiv paper

**Comment by elisejiuqizhang** [comment]
Ah I see! The name I typed wasn't correct, going to fix that. Thanks for pointing it out!
